version: '3.5'
services:
  db:
    image: postgres
    container_name: petshop_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshop
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/data:/var/lib/postgresql/data
    user: 1000:1000
    networks:
      - backend-network

  api:  
    build: .
    container_name: petshop_api
    tty: true
    stdin_open: true
    restart: always
    environment:
      TYPEORM_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge